# Name displayed in GitHub Actions tab
# This is the title of your CI pipeline
name: Run Checkout Tests

# "on" means what event should trigger this workflow
on:

  # Start workflow whenever code is pushed to repository
  push:

    # Only run when push is made to main branch
    branches: [ main ]

# "jobs" contains all tasks GitHub Actions must perform
jobs:

  # Internal job name
  # This job will run your checkout tests
  checkout-test:

    # GitHub creates a temporary virtual machine
    # ubuntu-latest = latest stable Ubuntu Linux image
    runs-on: ubuntu-latest

    # "steps" run from top to bottom in order
    steps:

      # Step title visible in pipeline logs
      - name: Download repository code

        # Official GitHub action
        # Downloads your project files from GitHub
        # Without this, the machine has no code to test
        uses: actions/checkout@v4

      # Step title visible in pipeline logs
      - name: Install Node.js

        # Official GitHub action
        # Installs Node.js runtime on temporary machine
        # Needed for npm, npx, Playwright, Cucumber
        uses: actions/setup-node@v4

        # Extra configuration for setup-node action
        with:

          # Install Node.js version 20
          # Good stable version for modern test frameworks
          node-version: 20

      # Step title visible in logs
      - name: Install project packages

        # Reads package.json and installs all dependencies
        # Example:
        # playwright
        # @cucumber/cucumber
        # typescript
        # ts-node
        # multiple-cucumber-html-reporter
        run: npm install

      # Step title visible in logs
      - name: Install Playwright browsers and Linux dependencies

        # Downloads browsers used by Playwright:
        # Chromium
        # Firefox
        # WebKit (Safari engine)
        #
        # --with-deps also installs Linux libraries required
        # for browser launch inside Ubuntu runner
        #
        # This fixes missing library errors such as:
        # libgtk
        # libgraphene
        # libsecret
        # etc
        run: npx playwright install --with-deps

        # Final test execution step
      - name: Run checkout feature tests in single thread

        # Run checkout scenarios one by one
        # Prevents CI runner conflicts with mobile browsers
        # More stable than parallel execution in GitHub Actions
        run: npx cucumber-js features/checkout.feature --parallel 1

      # Deployment step runs only if all earlier steps passed
      - name: Deploy Demo Build

        # This simulates a deployment action
        # GitHub runner prints success message in logs
        run: echo "Deployment successful"